name: "Sample App"
description: "Sample application for testing"
url: "https://localhost:3000"
logo_url: "https://localhost:3000/logo.png"
auth_flow_graph_id: "auth_flow_config_basic"
registration_flow_graph_id: "registration_flow_config_basic"
is_registration_flow_enabled: true
user_attributes:
  - "given_name"
  - "family_name"
  - "email"
  - "groups"
inbound_auth_config:
  - type: "oauth2"
    config:
      client_id: "{{ .CLIENT_ID }}"
      redirect_uris:
        {{- range .REDIRECT_URIS}}
          - {{.}}
        {{- end}}
      grant_types:
        - "authorization_code"
      response_types:
        - "code"
      token_endpoint_auth_method: "none"
      pkce_required: true
      public_client: true
      token:
        issuer: "thunder"
        access_token:
          validity_period: 3600
          user_attributes:
            - "given_name"
            - "family_name"
            - "email"
            - "groups"
        id_token:
          validity_period: 3600
          user_attributes:
            - "given_name"
            - "family_name"
            - "email"
            - "groups"
          scope_claims:
            profile:
              - "name"
              - "given_name"
              - "family_name"
              - "picture"
            email:
              - "email"
              - "email_verified"
            phone:
              - "phone_number"
              - "phone_number_verified"
            group:
              - "groups"
